#!/bin/bash
# =============================================================================
# Docker Entrypoint Script for Frontend Container
# =============================================================================
# This script runs when the container starts and performs:
# 1. Generates env.js with runtime environment variables
# 2. Starts Nginx in the foreground
#
# Why this is needed:
# - React apps are compiled at build time, so environment variables are baked in
# - To change API URLs between dev/staging/prod without rebuilding:
#   * Generate a JavaScript file with runtime config
#   * Load it in index.html before the app bundle
#   * Access via window.ENV in the React app
#
# Usage:
# - Set VITE_API_BASE_URL environment variable in Azure Container Apps
# - This script will generate /usr/share/nginx/html/config/env.js
# - React app can access it via: window.ENV.API_BASE_URL
# =============================================================================

set -e  # Exit on any error

echo "🚀 Starting Factory Agent Frontend..."

# =============================================================================
# Generate Runtime Environment Configuration
# =============================================================================
echo "📝 Generating runtime environment configuration..."

# Create config directory if it doesn't exist
mkdir -p /usr/share/nginx/html/config

# Generate env.js with runtime environment variables
# This file is loaded by index.html and makes variables available via window.ENV
cat > /usr/share/nginx/html/config/env.js <<EOF
// =============================================================================
// Runtime Environment Configuration
// =============================================================================
// This file is auto-generated by docker-entrypoint.sh at container startup.
// It provides runtime configuration to the React app without requiring a rebuild.
//
// Usage in React:
//   const apiBaseUrl = window.ENV?.API_BASE_URL || 'http://localhost:8000';
//
// DO NOT EDIT THIS FILE MANUALLY - it will be overwritten on container restart.
// =============================================================================

window.ENV = {
  API_BASE_URL: '${VITE_API_BASE_URL:-http://localhost:8000}',
  NODE_ENV: '${NODE_ENV:-production}',
  VERSION: '${APP_VERSION:-unknown}',
  BUILD_DATE: '$(date -u +"%Y-%m-%dT%H:%M:%SZ")',
};

console.log('✅ Runtime environment configuration loaded:', window.ENV);
EOF

echo "✅ Runtime environment configuration generated:"
cat /usr/share/nginx/html/config/env.js

# =============================================================================
# Update index.html to Load Runtime Config
# =============================================================================
# Check if env.js script tag is already in index.html
if ! grep -q "/config/env.js" /usr/share/nginx/html/index.html; then
    echo "📝 Updating index.html to load runtime configuration..."

    # Insert script tag before closing </head> tag
    # This ensures env.js is loaded before the React app bundle
    sed -i 's|</head>|  <script src="/config/env.js"></script>\n  </head>|' /usr/share/nginx/html/index.html

    echo "✅ index.html updated with runtime config script"
else
    echo "✅ index.html already configured for runtime config"
fi

# =============================================================================
# Display Configuration
# =============================================================================
echo ""
echo "🌍 Environment Configuration:"
echo "  - API_BASE_URL: ${VITE_API_BASE_URL:-http://localhost:8000}"
echo "  - NODE_ENV: ${NODE_ENV:-production}"
echo "  - APP_VERSION: ${APP_VERSION:-unknown}"
echo ""

# =============================================================================
# Start Nginx
# =============================================================================
echo "🚀 Starting Nginx..."

# Start Nginx in the foreground
# -g "daemon off;" keeps Nginx running in the foreground (required for Docker)
exec nginx -g "daemon off;"
